DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS Books;

-- Create Authors Table
CREATE TABLE Authors (
    AuthorID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    BirthYear INTEGER
);

-- Create Books Table
CREATE TABLE Books (
    BookID INTEGER PRIMARY KEY,
    Title TEXT NOT NULL,
    AuthorID INTEGER,
    Genre TEXT,
    IsAvailable BOOLEAN DEFAULT TRUE,
    Owner TEXT CHECK(Owner IN ('Cait', 'Zach')),
    FOREIGN KEY (AuthorID) REFERENCES Authors(AuthorID)
);


-- Author Data
INSERT INTO Authors (Name, BirthYear) VALUES
('Neil Gaiman', 1960),
('Katherine Peterson', 1932),
('Thomas Craughwell', 1956),
('Dan Harris', 1971),
('Susanna Kaysen', 1948),
('Steve Martin', 1945),
('Marie Lu', 1984),
('Wil Wheaton', 1972),
('Robert Stroud', 1890),
('Peter Filichia', 1946), --10
('Nicholas Sparks', 1965),
('Maya Angelou', 1928),
('Augusten Burroughs', 1965),
('Tim Sandlin', 1950),
('David Sedaris', 1956),
('Chuck Klosterman', 1972),
('Dale McGowan', 1963),
('Richard P. Feynman', 1918),
('Tawni O''Dell', 1964),
('James Patterson', 1947), --20
('Yuval Harari', 1976),
('Cheryl Strayed', 1968),
('Alan Rickman', 1946),
('Brent Spiner', 1949),
('Tom Felton', 1987),
('Jonathan Franzen', 1959),
('Allie Brosh', 1985),
('Shea Serrano', 1981),
('Matthew Inman', 1982),
('Mike Majlak', 1985), --30
('John Scalzi', 1969), 
('A.J. Jacobs', 1968),
('Bo Burnham', 1990),
('Trevor Noah', 1984),
('Jane Zei', NULL),
('Kelly Mahon', 1988),
('Philip Pullman', 1946),
('Robert Fulghum', 1937),
('Rob Sheffield', 1966),
('Daniel Keyes', 1927), --40
('John Robison', 1957), 
('David Wroblewski', 1959),
('Jonathan Foer', 1977),
('Karl Marx', 1818),
('Charles Dickens', 1812),
('Daniel Tammet', 1979),
('Tom Clancy', 1947),
('Robert Ludlum', 1927),
('J.D. Salinger', 1919),
('Tom Corbett, Stearn Robinson', NULL), --50
('Ray Bradbury', 1920),
('Mark Twain', 1835), 
('Edgar Allan Poe', 1809), 
('John Milton', 1608), 
('John Steinbeck', 1902),
('Judy Scott', 1947),
('Charlotte Brontë', 1816),
('O.T. Nelson', 1928), 
('Douglas Adams', 1952),
('Jack London', 1876), --60
('Mick Mars, Vince Neil, Nikki Sixx, Tommy Lee, Neil Strauss', NULL),
('Bradford Angier', 1910),
('Johanna Spyri', 1827),
('Cory Doctorow', 1971),
('Jane Austen', 1775),
('Barbara Kingsolver', 1955),
('Rupert Sheldrake', 1942),
('Meg Rosoff', 1956),
('Kurt Vonnegut', 1922),
('Arthur C. Clarke', 1917),
('Mark Haddon', 1962),
('Aldous Huxley', 1894),
('Alka Joshi', 1958),
('Jack Kerouac', 1922),
('David Gomberg, Justin Heimberg', NULL),
('Reginald Rose', 1920),  
('Stephen King', 1947),
('Anne Rice', 1941),
('John Grisham', 1955),
('Robin MacNaughton', 1947),
('Yann Martel', 1963),
('Ta-Nehisi Coates', 1975),
('J.K. Rowling', 1965),
('Patrick Ness', 1971),
('Jennifer Lynn Barnes', 1984),
('Gary Larson', 1950), 
('Matz', 1967),
('David Wild', 1961),
('Vivek J. Tiwary, Andrew C. Robinson, Kyle Baker', NULL),
('Terry Jones', 1942),
('Lewis Carroll', 1832),
('William Shakespeare', 1564),
('Wally Lamb', 1950),
('Will Pearson', 1979), 
('Eric Clapton', 1945),
('George Carlin', 1937),
('Emily Brontë', 1818),
('Frank Herbert', 1920),
('Andy Weir', 1972),
('Adam Silvera', 1990),
('Don Miguel Ruiz', 1952);


-- Book Data
INSERT INTO Books (Title, AuthorID, Genre, Owner) VALUES
('Neverwhere', (SELECT AuthorID FROM Authors WHERE Name = 'Neil Gaiman'), 'Fantasy', 'Cait'),
('Jacob Have I Loved', (SELECT AuthorID FROM Authors WHERE Name = 'Katherine Peterson'), 'Coming-of-Age', 'Cait'),
('The Baby on the Car Roof', (SELECT AuthorID FROM Authors WHERE Name = 'Thomas Craughwell'), 'Humor', 'Cait'),
('10% Happier', (SELECT AuthorID FROM Authors WHERE Name = 'Dan Harris'), 'Self-Help', 'Cait'),
('Girl, Interrupted', (SELECT AuthorID FROM Authors WHERE Name = 'Susanna Kaysen'), 'Mental Health', 'Cait'),
('Born Standing Up', (SELECT AuthorID FROM Authors WHERE Name = 'Steve Martin'), 'Comedy', 'Cait'),
('Legend', (SELECT AuthorID FROM Authors WHERE Name = 'Marie Lu'), 'Dystopian', 'Cait'),
('Prodigy', (SELECT AuthorID FROM Authors WHERE Name = 'Marie Lu'), 'Dystopian', 'Cait'),
('Champion', (SELECT AuthorID FROM Authors WHERE Name = 'Marie Lu'), 'Dystopian', 'Cait'),
('The Happiest Days of Our Lives', (SELECT AuthorID FROM Authors WHERE Name = 'Wil Wheaton'), 'Memoir', 'Cait'),
('Stroud''s Digest on the Diseases of Birds', (SELECT AuthorID FROM Authors WHERE Name = 'Robert Stroud'), 'Veterinary Science', 'Cait'),
('Let''s Put on a Musical!', (SELECT AuthorID FROM Authors WHERE Name = 'Peter Filichia'), 'Theater', 'Cait'),
('The Notebook', (SELECT AuthorID FROM Authors WHERE Name = 'Nicholas Sparks'), 'Romance', 'Cait'),
('The Collected Autobiographies of Maya Angelou', (SELECT AuthorID FROM Authors WHERE Name = 'Maya Angelou'), 'Autobiography', 'Cait'),
('A Wolf at the Table', (SELECT AuthorID FROM Authors WHERE Name = 'Augusten Burroughs'), 'True Crime', 'Cait'),
('Honey, Don''t', (SELECT AuthorID FROM Authors WHERE Name = 'Tim Sandlin'), 'Mystery', 'Cait'),
('When You Are Engulfed in Flames', (SELECT AuthorID FROM Authors WHERE Name = 'David Sedaris'), 'Humor', 'Cait'),
('Eating the Dinosaur', (SELECT AuthorID FROM Authors WHERE Name = 'Chuck Klosterman'), 'Nonfiction', 'Cait'),
('Parenting Beyond Belief', (SELECT AuthorID FROM Authors WHERE Name = 'Dale McGowan'), 'Philosophy', 'Cait'),
('Perfectly Reasonable Deviations', (SELECT AuthorID FROM Authors WHERE Name = 'Richard P. Feynman'), 'Biography', 'Cait'),
('Backroads', (SELECT AuthorID FROM Authors WHERE Name = 'Tawni O''Dell'), 'Thriller', 'Cait'),
('Mary, Mary', (SELECT AuthorID FROM Authors WHERE Name = 'James Patterson'), 'Mystery', 'Cait'),
('Sapiens', (SELECT AuthorID FROM Authors WHERE Name = 'Yuval Harari'), 'History', 'Zach'),
('Wild', (SELECT AuthorID FROM Authors WHERE Name = 'Cheryl Strayed'), 'Adventure', 'Cait'),
('Madly, Deeply', (SELECT AuthorID FROM Authors WHERE Name = 'Alan Rickman'), 'Biography', 'Cait'),
('Fan Fiction', (SELECT AuthorID FROM Authors WHERE Name = 'Brent Spiner'), 'Humor', 'Cait'),
('Beyond the Wand', (SELECT AuthorID FROM Authors WHERE Name = 'Tom Felton'), 'Autobiography', 'Cait'),
('Freedom', (SELECT AuthorID FROM Authors WHERE Name = 'Jonathan Franzen'), 'Drama', 'Cait'),
('Solutions and Other Problems', (SELECT AuthorID FROM Authors WHERE Name = 'Allie Brosh'), 'Comedy', 'Cait'),
('Movies (and Other Things)', (SELECT AuthorID FROM Authors WHERE Name = 'Shea Serrano'), 'Humor', 'Cait'),
('How to Tell if Your Cat is Plotting to Kill You', (SELECT AuthorID From Authors WHERE Name = 'Matthew Inman'), 'Humor', 'Cait'),
('The Fifth Vital', (SELECT AuthorID FROM Authors WHERE Name = 'Mike Majlak'), 'Humor', 'Zach'),
('Redshirts', (SELECT AuthorID FROM Authors WHERE Name = 'John Scalzi'), 'Science Fiction', 'Cait'),
('The Know-It-All', (SELECT AuthorID FROM Authors WHERE Name = 'A.J. Jacobs'), 'Nonfiction', 'Cait'),
('Egghead', (SELECT AuthorID FROM Authors WHERE Name = 'Bo Burnham'), 'Poetry', 'Cait'),
('Hyperbole and a Half', (SELECT AuthorID FROM Authors WHERE Name = 'Allie Brosh'), 'Humor', 'Cait'),
('Born a Crime', (SELECT AuthorID FROM Authors WHERE Name = 'Trevor Noah'), 'Biography', 'Cait'),
('What Do You Care What Other People Think?', (SELECT AuthorID FROM Authors WHERE Name = 'Richard P. Feynman'), 'Science', 'Cait'),
('Success is 90% Spite', (SELECT AuthorID FROM Authors WHERE Name = 'Jane Zei'), 'Self-Help', 'Cait'),
('Race Me in a Lobster Suit', (SELECT AuthorID FROM Authors WHERE Name = 'Kelly Mahon'), 'Humor', 'Cait'),
('All I Really Need to Know I Learned in Kindergarten', (SELECT AuthorID FROM Authors WHERE Name = 'Robert Fulghum'), 'Philosophy', 'Cait'),
('Love is a Mix Tape', (SELECT AuthorID FROM Authors WHERE Name = 'Rob Sheffield'), 'Music', 'Cait'),
('Golden Compass', (SELECT AuthorID FROM Authors WHERE Name = 'Philip Pullman'), 'Fantasy', 'Cait'),
('Subtle Knife', (SELECT AuthorID FROM Authors WHERE Name = 'Philip Pullman'), 'Fantasy', 'Cait'),
('Amber Spyglass', (SELECT AuthorID FROM Authors WHERE Name = 'Philip Pullman'), 'Fantasy', 'Cait'),
('Flowers for Algernon', (SELECT AuthorID FROM Authors WHERE Name = 'Daniel Keyes'), 'Science Fiction', 'Cait'),
('Look Me in the Eye', (SELECT AuthorID FROM Authors WHERE Name = 'John Robison'), 'Memoir', 'Cait'),
('American Gods', (SELECT AuthorID FROM Authors WHERE Name = 'Neil Gaiman'), 'Fantasy', 'Cait'),
('The Story of Edgar Sawtelle', (SELECT AuthorID FROM Authors WHERE Name = 'David Wroblewski'), 'Mystery', 'Cait'),
('Extremely Loud & Incredibly Close', (SELECT AuthorID FROM Authors WHERE Name = 'Jonathan Foer'), 'Fiction', 'Cait'),
('Running with Scissors', (SELECT AuthorID FROM Authors WHERE Name = 'Augusten Burroughs'), 'Memoir', 'Cait'),
('The Communist Manifesto', (SELECT AuthorID FROM Authors WHERE Name = 'Karl Marx'), 'Political Theory', 'Cait'),
('Great Expectations', (SELECT AuthorID FROM Authors WHERE Name = 'Charles Dickens'), 'Classic', 'Cait'),
('Surely You''re Joking, Mr. Feynman!', (SELECT AuthorID FROM Authors WHERE Name = 'Richard P. Feynman'), 'Biography', 'Cait'),
('Born on a Blue Day', (SELECT AuthorID FROM Authors WHERE Name = 'Daniel Tammet'), 'Memoir', 'Cait'),
('The Hunt for Red October', (SELECT AuthorID From Authors WHERE Name = 'Tom Clancy'), 'Thriller', 'Cait'),
('The Bourne Identity', (SELECT AuthorID FROM Authors WHERE Name = 'Robert Ludlum'), 'Thriller', 'Cait'),
('The Bourne Ultimatum', (SELECT AuthorID FROM Authors WHERE Name = 'Robert Ludlum'), 'Thriller', 'Cait'),
('The Bourne Supremacy', (SELECT AuthorID FROM Authors WHERE Name = 'Robert Ludlum'), 'Thriller', 'Cait'),
('It Was on Fire When I Lay Down on it', (SELECT AuthorID FROM Authors WHERE Name = 'Robert Fulghum'), 'Philosophy', 'Cait'),
('The Catcher in the Rye', (SELECT AuthorID FROM Authors WHERE Name = 'J.D. Salinger'), 'Coming-of-Age', 'Cait'),
('The Dreamer''s Dictionary', (SELECT AuthorID FROM Authors WHERE Name = 'Tom Corbett, Stearn Robinson'), 'Poetry', 'Cait'),
('Fahrenheit 451', (SELECT AuthorID FROM Authors WHERE Name = 'Ray Bradbury'), 'Dystopian', 'Cait'),
('The Adventures of Huckleberry Finn', (SELECT AuthorID FROM Authors WHERE Name = 'Mark Twain'), 'Classic', 'Cait'),
('Paradise Lost', (SELECT AuthorID FROM Authors WHERE Name = 'John Milton'), 'Classic', 'Cait'),
('The Grapes of Wrath', (SELECT AuthorID FROM Authors WHERE Name = 'John Steinbeck'), 'Historical Fiction', 'Cait'),
('Leonard, Marianne, and Me', (SELECT AuthorID From Authors WHERE Name = 'Judy Scott'), 'Memoir', 'Cait'),
('Jane Eyre', (SELECT AuthorID FROM Authors WHERE Name = 'Charlotte Brontë'), 'Classic', 'Cait'),
('The Girl who Owned a City', (SELECT AuthorID FROM Authors WHERE Name = 'O.T. Nelson'), 'Science Fiction', 'Cait'),
('The Call of the Wild and White Fang', (SELECT AuthorID FROM Authors WHERE Name = 'Jack London'), 'Adventure', 'Cait'),
('The Hitchhiker''s Guide to the Galaxy', (SELECT AuthorID FROM Authors WHERE Name = 'Douglas Adams'), 'Science Fiction', 'Cait'),
('The Dirt: Confessions of the World''s Most Notorious Rock Band', (SELECT AuthorID FROM Authors WHERE Name = 'Mick Mars, Vince Neil, Nikki Sixx, Tommy Lee, Neil Strauss'), 'Autobiography', 'Cait'),
('How to Stay Alive in the Woods', (SELECT AuthorID FROM Authors WHERE Name = 'Bradford Angier'), 'Reference Work', 'Cait'),
('Heidi', (SELECT AuthorID FROM Authors WHERE Name = 'Johanna Spyri'), 'Children''s Fiction', 'Cait'),
('The Rapture of the Nerds', (SELECT AuthorID FROM Authors WHERE Name = 'Cory Doctorow'), 'Science Fiction', 'Cait'),
('Little Brother', (SELECT AuthorID FROM Authors WHERE Name = 'Cory Doctorow'), 'Young Adult', 'Cait'),
('Down and Out in the Magic Kingdom', (SELECT AuthorID FROM Authors WHERE Name = 'Cory Doctorow'), 'Science Fiction', 'Cait'),
('Emma', (SELECT AuthorID FROM Authors WHERE Name = 'Jane Austen'), 'Romance', 'Cait'),
('Sense and Sensibility', (SELECT AuthorID FROM Authors WHERE Name = 'Jane Austen'), 'Romance', 'Cait'),
('Pride and Prejudice', (SELECT AuthorID FROM Authors WHERE Name = 'Jane Austen'), 'Romance', 'Cait'),
('Wuthering Heights', (SELECT AuthorID FROM Authors WHERE Name = 'Emily Brontë'), 'Gothic Fiction', 'Cait'),
('Prodigal Summer', (SELECT AuthorID FROM Authors WHERE Name = 'Barbara Kingsolver'), 'Domestic Fiction', 'Cait'),
('The Presence of the Past', (SELECT AuthorID FROM Authors WHERE Name = 'Rupert Sheldrake'), 'Nonfiction', 'Cait'),
('How I Live Now', (SELECT AuthorID FROM Authors WHERE Name = 'Meg Rosoff'), 'Young Adult', 'Cait'),
('Cat''s Cradle', (SELECT AuthorID FROM Authors WHERE Name = 'Kurt Vonnegut'), 'Science Fiction', 'Cait'),
('2001: A Space Odyssey', (SELECT AuthorID FROM Authors WHERE Name = 'Arthur C. Clarke'), 'Science Fiction', 'Cait'),
('The Curious Incident of the Dog in the Night-time', (SELECT AuthorID FROM Authors WHERE Name = 'Mark Haddon'), 'Mystery', 'Cait'),
('Brave New World', (SELECT AuthorID FROM Authors WHERE Name = 'Aldous Huxley'), 'Dystopian', 'Cait'),
('The Henna Artist', (SELECT AuthorID FROM Authors WHERE Name = 'Alka Joshi'), 'Historical Fiction', 'Cait'),
('On the Road', (SELECT AuthorID FROM Authors WHERE Name = 'Jack Kerouac'), 'Autobiography', 'Cait'),
('Squirrel Seeks Chipmunk', (SELECT AuthorID FROM Authors WHERE Name = 'David Sedaris'), 'Humor', 'Cait'),
('Of Mice and Men', (SELECT AuthorID FROM Authors WHERE Name = 'John Steinbeck'), 'Tragedy', 'Cait'),
('Do Unto Others', (SELECT AuthorID FROM Authors WHERE Name = 'David Gomberg, Justin Heimberg'), 'Humor', 'Cait'),
('Twelve Angry Men', (SELECT AuthorID FROM Authors WHERE Name = 'Reginald Rose'), 'Drama', 'Cait'),
('Tom Clancy Rainbow Six', (SELECT AuthorID FROM Authors WHERE Name = 'Tom Clancy'), 'Crime Fiction', 'Cait'),
('Hearts in Atlantis', (SELECT AuthorID FROM Authors WHERE Name = 'Stephen King'), 'Horror', 'Cait'),
('The Vampire Lestat', (SELECT AuthorID FROM Authors WHERE Name = 'Anne Rice'), 'Gothic Fiction', 'Cait'),
('The Brethren', (SELECT AuthorID FROM Authors WHERE Name = 'John Grisham'), 'Mystery', 'Cait'),
('Robin MacNaughton''s Sun Sign Personality Guide', (SELECT AuthorID FROM Authors WHERE Name = 'Robin MacNaughton'), 'Astrology', 'Cait'),
('From Beginning to End: the Rituals of Our Lives', (SELECT AuthorID FROM Authors WHERE Name = 'Robert Fulghum'), 'Self-help', 'Cait'),
('Life of Pi', (SELECT AuthorID FROM Authors WHERE Name = 'Yann Martel'), 'Survival', 'Cait'),
('The Water Dancer', (SELECT AuthorID FROM Authors WHERE Name = 'Ta-Nehisi Coates'), 'Fantasy', 'Cait'),
('The Tales of Beedle the Bard', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Fantastic Beasts & Where to Find Them', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Quidditch Through the Ages', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('The Knife of Never Letting Go', (SELECT AuthorID FROM Authors WHERE Name = 'Patrick Ness'), 'Science Fiction', 'Cait'),
('Possible Side Effects', (SELECT AuthorID FROM Authors WHERE Name = 'Augusten Burroughs'), 'Humor', 'Cait'),
('The Naturals', (SELECT AuthorID FROM Authors WHERE Name = 'Jennifer Lynn Barnes'), 'Mystery', 'Cait'),
('Killer Instinct', (SELECT AuthorID FROM Authors WHERE Name = 'Jennifer Lynn Barnes'), 'Mystery', 'Cait'),
('All In', (SELECT AuthorID FROM Authors WHERE Name = 'Jennifer Lynn Barnes'), 'Mystery', 'Cait'),
('Unnatural Selections', (SELECT AuthorID FROM Authors WHERE Name = 'Gary Larson'), 'Humor', 'Cait'),
('Snow Piercer The Prequel Part One: Extinction', (SELECT AuthorID FROM Authors WHERE Name = 'Matz'), 'Science Fiction', 'Cait'),
('Snow Piercer The Prequel Part Two: Apocalypse', (SELECT AuthorID FROM Authors WHERE Name = 'Matz'), 'Science Fiction', 'Cait'),
('Friends...''Til the End', (SELECT AuthorID FROM Authors WHERE Name = 'David Wild'), 'Biography', 'Cait'),
('The Fifth Beatle: The Brian Epstein Story', (SELECT AuthorID FROM Authors WHERE Name = 'Vivek J. Tiwary, Andrew C. Robinson, Kyle Baker'), 'Biography', 'Cait'),
('Lady Cottington''s Pressed Fairy Book', (SELECT AuthorID FROM Authors WHERE Name = 'Terry Jones'), 'Humor', 'Cait'),
('Alice''s Adventures in Wonderland', (SELECT AuthorID FROM Authors WHERE Name = 'Lewis Carroll'), 'Fantasy', 'Cait'),
('William Shakespeare: The Complete Works', (SELECT AuthorID FROM Authors WHERE Name = 'William Shakespeare'), 'Various Genres', 'Cait'),
('The Hour I First Believed', (SELECT AuthorID FROM Authors WHERE Name = 'Wally Lamb'), 'Psychological Fiction', 'Cait'),
('Mental Floss Presents Condensed Knowledge: A Deliciously Irreverent Guide to Feeling Smart Again', (SELECT AuthorID FROM Authors WHERE Name = 'Will Pearson'), 'Reference Work', 'Cait'), 
('Chapter: The Autobiography', (SELECT AuthorID FROM Authors WHERE Name = 'Eric Clapton'), 'Autobiography', 'Cait'),
('Three Times Carlin: An Orgy of George', (SELECT AuthorID FROM Authors WHERE Name = 'George Carlin'), 'Humor', 'Cait'),
('Harry Potter and the Sorcerer''s Stone', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Harry Potter and the Chamber of Secrets', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Harry Potter and the Prisoner of Azkaban', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Harry Potter and the Goblet of Fire', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Harry Potter and the Order of the Phoenix', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Harry Potter and the Half-Blood Prince', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Harry Potter and the Deathly Hallows', (SELECT AuthorID FROM Authors WHERE Name = 'J.K. Rowling'), 'Fantasy', 'Cait'),
('Dune', (SELECT AuthorID FROM Authors WHERE Name = 'Frank Herbert'), 'Science Fiction', 'Zach'),
('Artemis', (SELECT AuthorID FROM Authors WHERE Name = 'Andy Weir'), 'Science Fiction', 'Cait'),
('The First to Die at the End', (SELECT AuthorID FROM Authors WHERE Name = 'Adam Silvera'), 'Young Adult', 'Zach'),
('The Four Agreements', (SELECT AuthorID FROM Authors WHERE Name = 'Don Miguel Ruiz'), 'Self-help', 'Zach');